global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "alerts/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apex-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-engine:8001']

  - job_name: 'apex-data'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-data:8002']

  - job_name: 'apex-ml'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-ml:8003']

  - job_name: 'apex-ai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-ai:8004']

  - job_name: 'apex-p2p'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-p2p:8005']

  - job_name: 'apex-executor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex-executor:8006']
